name: http

on:
  push:
    paths:
      - http/**
      - .github/workflows/http.yml

defaults:
  run:
    working-directory: ./http

jobs:
  lint-test:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-lint-test
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install pgvector
        run: |
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
          sudo apt-get install postgresql-14-pgvector

      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-http-${{ hashFiles('http/setup.py') }}

      - name: pip install
        run: |
          pip install pip==23.*
          pip install .[test]

      - name: lint
        run: make lint

      - name: test
        run: make test

  check-version-changed:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wait 10s
        run: sleep 10  # in case the pr is very new
      - name: Get changed files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          changed=$(gh pr diff --name-only)
          echo Changed files:
          echo $changed
          if [[ $changed != *"http/src/moomoo_http/version"* ]]; then
            echo "No changes to version file"
            exit 1
          fi

